# // Changelogs Date  | Author                | Description
# // 2023-12-23       | Anthony Coudène       | Creation

@baseUrl = https://localhost:7138/odata

### Get Metadata
GET {{baseUrl}}/$metadata

### Get all super heroes
GET {{baseUrl}}/SuperHeros

